#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'rvm',
  git: 'git://github.com/fnichol/chef-rvm.git', ref: 'v0.9.0'
cookbook 'postgis',
  git: 'git://github.com/realityforge/chef-postgis.git'
