default: &default
  tilemill_path: '/usr/share/tilemill'
  redis_url: <%= ENV["REDIS_URL"] %>
  carto_db:
    username: <%= ENV["CARTODB_USERNAME"] %>
    api_key: <%= ENV["CARTODB_API_KEY"] %>

development:
  <<: *default
  projectmill_path: '$HOME/dependencies/projectmill'

test:
  <<: *default
  projectmill_path: '$HOME/dependencies/projectmill'

staging:
  <<: *default
  projectmill_path: '$HOME/dependencies/projectmill'


production:
  <<: *default
  projectmill_path: '$HOME/dependencies/projectmill'
