postgis: &postgis
  adapter: postgis
  encoding: unicode
  pool: 5
  username: postgres
  password:
  script_dir: /usr/share/postgresql/9.2/contrib/postgis-2.0
  template: template_postgis

development:
  <<: *postgis
  database: bluecarbon_development

test: &test
  <<: *postgis
  database: bluecarbon_test

cucumber:
  <<: *test
