default: &default
  adapter: postgresql
  encoding: unicode
  min_messages: WARNING

  database: bluecarbon_<%= Rails.env %>
  pool: 5

  host: <%= ENV.fetch('DB_HOST') %>
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>


development:
  <<: *default
  adapter: postgis
  template: template_postgis

test:
  <<: *default
  adapter: postgis
  template: template_postgis

staging:
  <<: *default
  pool: 10

production:
  <<: *default
  pool: 10
