postgis: &postgis
  adapter: postgis
  encoding: unicode
  pool: 5
  username: postgres
  password:
  template: template_postgis

development:
  <<: *postgis
  database: bluecarbon_development

test: &test
  <<: *postgis
  database: bluecarbon_test

cucumber:
  <<: *test
